version: "3.9"
services:
  mongodb:
    image: mongo
    container_name: ledger-mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongo/database:/data/db
    ports:
      - 27019:27017
    restart: unless-stopped
